[project]
name = "vercel-chatbot-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi=0.109.2",
    "google-generativeai>=0.3.1",
    "httpx=0.25.2",
    "uvicorn>=0.25.0",
    "pydantic>=2.0.0"
]
